### ISSUE TITLE
현재 진행중인 세션에 대한 정보가 있어야될거 같네요!

### ISSUE THREAD

**Issue by paulsoh** [idiots-io/blueberry#11]
지금 현재 reducer내에서는 
sessions, todos, settings만 있는데 생각해보니 지금 진행중인 세션이 있는지, 있다면 진행중인지 일시 정지 상태인지, 얼마나 진행중인지에 대한 정보가 없네요

진행중인 상태에서 다른 탭 왔다갔다할 수 있으니 요 정보를 redux state에 담으면 좋을거 같아요
* session이 진행중이면 세팅쪽 수정 안되게도 막아놔야겠네요

다음과 같은 값들을 넣으면 좋을거 같아요
isSessionRunning: bool
sessionProgress: number(초)
sessionDuration: number(정해진 세션 시간, ex. 25분)

추가 적으로 필요한 값들 있으면 의견 주세용

**Comment by gloorx** [comment]
세션 진행중일 때 세션 수정 안되게 한다면 sessionDuration은 settings에서 가져올 수 있으니 없어도 될 것 같아.
저거와 더불어서 현재 진행중인 세션이 어느 투두인지 저장할 필요도 있을듯
